refactory done

diff --git a/devtools/hybridmeter_dev b/devtools/hybridmeter_dev
--- a/devtools/hybridmeter_dev
+++ b/devtools/hybridmeter_dev
@@ -2,25 +2,48 @@
 
 ORIGIN_PWD=${PWD}
 
+BCR="\n\n\n"
+LCR="\n\n"
+ITAB="\t\t\t\t"
+
 help="hybridmeter_dev, the all-in-one tool for continuous integration of hybridmeter
-     \n\nUsage : hybridmeter_dev [-help|-h] [--] <autoconfig MOODLE_ROOT|autostage|build|stage> 
-     \n\nautoconfig MOODLE_ROOT\tAdd moodle root path and git root path in the hybrid_dev.env file
-     \nautostage\t\tStage changes to local moodle immediately and when they are changes in the codebase
-     \nbuild\t\t\tBuild ZIP file of the plugin for deployment
-     \nstage\t\t\tStage changes to local moodle only once
-     \n\nOptions :
-     \n\t--help|-h\tDisplay this screen
-     \n\n2022 ISAE-Supaero"
+     ${LCR}Usage : hybridmeter_dev [-help|-h] [--] <autoconfig MOODLE_ROOT|autostage|build|stage> 
+     ${BCR}autoconfig MOODLE_ROOT\t\tAdd moodle root path and git root path in the hybrid_dev.env file
+     ${LCR}autostage\t\t\tStage changes to local moodle immediately and watch for changes
+     \n${ITAB}in the codebase
+     ${LCR}build\t\t\t\tBuild ZIP file of the plugin for deployment
+     ${LCR}stage\t\t\t\tStage changes to local moodle only once
+     ${BCR}Options :
+     \n\t--clear|-c\t\tClear terminal before every staging when autostage is enabled
+     \n\t--help|-h\t\tDisplay this screen
+     \n\t--keep-sass|-scss\tCompile SCSS file when staging even if compilation is disabled
+     \n\t--no-compilation|-nc\tDisable webpack compilation during staging
+     ${BCR}2022 ISAE-Supaero"
 
 VALID_MODES=("autoconfig" "autostage" "build" "stage")
+
+COMPILATION=1
+KEEP_SASS=0
+CLEAR=""
 
 in_options=1
 while [ $# -gt 0 ] && [ $in_options -eq 1 ]
 do
     case $1 in
+    --clear | -c)
+        CLEAR="-c"
+        shift
+        ;;
     --help | -h)
         echo -e $help
         exit 0
+        ;;
+    --keep-sass | -scss)
+        KEEP_SASS=1
+        shift
+        ;;
+    --no-compilation | -nc)
+        COMPILATION=0
         shift
         ;;
     --)
@@ -50,6 +73,8 @@ then
     SOURCE_PATH="${HYBRIDMETER_GIT_ROOT}/hybridmeter"
     DEVTOOLS_PATH="${HYBRIDMETER_GIT_ROOT}/devtools"
     VUE_PATH="${SOURCE_PATH}/vue"
+    VUE_STYLE_PATH="${VUE_PATH}/src/assets/style"
+    STYLE_PATH="${SOURCE_PATH}/assets/style"
     AMD_PATH="${SOURCE_PATH}/amd"
 else
     git_root_undefined=1
@@ -60,6 +85,7 @@ then
     MOODLE_ROOT=${HYBRIDMETER_MOODLE_ROOT}
     REPORT_PATH="${MOODLE_ROOT}/report"
     HYBRIDMETER_PATH="${REPORT_PATH}/hybridmeter"
+    THEME_PATH="${MOODLE_ROOT}/theme"
 else
     moodle_root_undefined=1
 fi
@@ -81,8 +107,10 @@ then
     fi
 
     moodle_root=$(readlink -f $1)
+    boost_scss_path=$(readlink -f "${moodle_root}/theme/boost/scss")
     git_root=$(readlink -f "${SCRIPT_DIR}/../")
     env_file="${SCRIPT_DIR}/hybrid_dev.env"
+    #vue_env_file="${git_root}/hybridmeter/vue/.env"
 
     if [ -f ${env_file} ]
     then
@@ -92,8 +120,17 @@ then
         touch ${env_file}
     fi
 
+    #if [ -f ${vue_env_file} ]
+    #then
+    #    sed '/MOODLE_BOOST_SCSS_PATH/d' ${vue_env_file} > ${vue_env_file}
+    #else
+    #    touch ${vue_env_file}
+    #fi
+
     echo "HYBRIDMETER_MOODLE_ROOT=\"${moodle_root}\"" >> ${env_file}
     echo "HYBRIDMETER_GIT_ROOT=\"${git_root}\"" >> ${env_file}
+
+    #echo "MOODLE_BOOST_SCSS_PATH=\"${boost_scss_path}\"" >> ${vue_env_file}
 
     echo "Environment ready"
     exit 0
@@ -107,30 +144,9 @@ elif [ $git_root_undefined -eq 1 ]
     then
         echo "[ERROR] The git root path isn't defined or isn't valid, please execute ./hybridemeter_dev autoconfig MOODLE_ROOT_PATH">&2
         exit 2
-elif [ $moodle_root_undefined -eq 1 ]
-    then
-        echo "[ERROR] The moodle root path isn't defined or isn't valid, please execute ./hybridemeter_dev autoconfig MOODLE_ROOT_PATH">&2
-        exit 3
 fi
 
-if [ "$1" = "autostage" ]
-then
-    while true
-    do
-        find ${SOURCE_PATH} -not -path "*hybridmeter/vue/node_modules*" | entr -dr bash ${DEVTOOLS_PATH}/stage_to_moodle.sh ${SOURCE_PATH} ${REPORT_PATH} ${VUE_PATH} ${AMD_PATH}
-        #TODO : forcer à recharger la page avec xdotool
-    done
-    exit 0
-elif [ "$1" = "stage" ]
-then
-    bash ${DEVTOOLS_PATH}/stage_to_moodle.sh ${SOURCE_PATH} ${REPORT_PATH} ${VUE_PATH} ${AMD_PATH}
-    error_code=$?
-    if [ $error_code -ne 0 ]
-    then
-        echo "[ERROR] An error occured during the stage, error code ${error_code}">&2
-        exit 4
-    fi
-elif [ "$1" = "build" ]
+if [ "$1" = "build" ]
 then
     cd ${VUE_PATH} && npm run build && cd ${OLDPWD}
     
@@ -157,6 +173,32 @@ then
         cd ${ORIGIN_PWD}
         echo "[ERROR] An error occured during the building of the zip file, error code ${error_code}">&2
         exit 5
+    fi
+fi
+
+if [ $moodle_root_undefined -eq 1 ]
+then
+    echo "[ERROR] The moodle root path isn't defined or isn't valid, please execute ./hybridemeter_dev autoconfig MOODLE_ROOT_PATH">&2
+    exit 3
+fi
+
+if [ "$1" = "autostage" ]
+then
+    while true
+    do
+        find ${SOURCE_PATH} -type f -name "*" ! -path "*hybridmeter/vue/node_modules*" ! -path "*hybridmeter/amd*" ! -path "*hybridmeter/vue/src/assets/themes*" | entr -d ${CLEAR} bash ${DEVTOOLS_PATH}/stage_to_moodle.sh ${SOURCE_PATH} ${REPORT_PATH} ${VUE_PATH} ${AMD_PATH} ${COMPILATION} ${KEEP_SASS}
+    done
+    exit 0
+elif [ "$1" = "stage" ]
+then
+    bash ${DEVTOOLS_PATH}/stage_to_moodle.sh ${SOURCE_PATH} ${REPORT_PATH} ${VUE_PATH} ${AMD_PATH} ${COMPILATION} ${KEEP_SASS}
+    error_code=$?
+    if [ $error_code -ne 0 ]
+    then
+        echo "[ERROR] An error occured during the stage, error code ${error_code}">&2
+        exit 4
+    else
+        exit 0
     fi
 else
     echo -e $help>&2
