CI tools updated : semantic changed and env file feature

diff --git a/devtools/hybridmeter_dev b/devtools/hybridmeter_dev
--- a/devtools/hybridmeter_dev
+++ b/devtools/hybridmeter_dev
@@ -1,35 +1,11 @@
 #!/bin/bash
 
-git_root_undefined=0
-moodle_root_undefined=0
-
-if [ -d "${HYBRIDMETER_GIT_ROOT}" ]
-then
-    SOURCE_PATH="${HYBRIDMETER_GIT_ROOT}/hybridmeter"
-    DEVTOOLS_PATH="${HYBRIDMETER_GIT_ROOT}/devtools"
-    VUE_PATH="${HYBRIDMETER_GIT_ROOT}/vue"
-else
-    git_root_undefined=1
-fi
-
-if [ -d "${HYBRIDMETER_MOODLE_ROOT_PATH}"]
-then
-    MOODLE_ROOT=${HYBRIDMETER_MOODLE_ROOT_PATH}
-    REPORT_PATH="${MOODLE_ROOT}/report"
-    HYBRIDMETER_PATH="${REPORT_PATH}/hybridmeter"
-else
-    moodle_root_undefined=1
-fi
-
-help="hybridmeter_dev usage : hybridmeter_dev [-help|-h] [--] <autocommit|commit|build|auto_config MOODLE_ROOT_PATH> 
-     \n\tautocommit : Commit changes to moodle immediately and when they are changes in codesource
-     \n\tcommit : Commit changes to moodle only once
+help="hybridmeter_dev usage : hybridmeter_dev [-help|-h] [--] <autostage|stage|build|auto_config MOODLE_ROOT_PATH> 
+     \n\tautostage : Stage changes to moodle immediately and when they are changes in codesource
+     \n\tstage : Stage changes to moodle only once
      \n\tbuild : build ZIP file for moodle
-     \n\tauto_config MOODLE_ROOT: Add script dir to path, moodle path and git root path in .bashrc
+     \n\tautoconfig MOODLE_ROOT: Add moodle path and git root path in the hybrid_dev.env file
      \n\t--help|-h : Display this screen"
-
-git_root_error="The git root path isn't defined or isn't valid, please launch ./hybridemeter_dev auto_config MOODLE_ROOT_PATH"
-moodle_root_error="The moodle root path isn't defined or isn't valid, please launch ./hybridemeter_dev auto_config MOODLE_ROOT_PATH"
 
 in_options=1
 while [ $# -gt 0 ] && [ $in_options -eq 1 ]
@@ -54,9 +30,37 @@ do
     esac
 done
 
-if [ "$1" = "auto_config" ]
+SCRIPT_PATH=$(readlink -f $0)
+SCRIPT_DIR=$(dirname $SCRIPT_PATH)
+
+. ${SCRIPT_DIR}/hybrid_dev.env
+
+git_root_undefined=0
+moodle_root_undefined=0
+
+if [ -d "${HYBRIDMETER_GIT_ROOT}" ]
 then
-    cp ~/.bashrc ~/.bashrc_backup
+    SOURCE_PATH="${HYBRIDMETER_GIT_ROOT}/hybridmeter"
+    DEVTOOLS_PATH="${HYBRIDMETER_GIT_ROOT}/devtools"
+    VUE_PATH="${SOURCE_PATH}/vue"
+else
+    git_root_undefined=1
+fi
+
+if [ -d "${HYBRIDMETER_MOODLE_ROOT}" ]
+then
+    MOODLE_ROOT=${HYBRIDMETER_MOODLE_ROOT}
+    REPORT_PATH="${MOODLE_ROOT}/report"
+    HYBRIDMETER_PATH="${REPORT_PATH}/hybridmeter"
+else
+    moodle_root_undefined=1
+fi
+
+git_root_error="The git root path isn't defined or isn't valid, please execute ./hybridemeter_dev autoconfig MOODLE_ROOT_PATH"
+moodle_root_error="The moodle root path isn't defined or isn't valid, please execute ./hybridemeter_dev autoconfig MOODLE_ROOT_PATH"
+
+if [ "$1" = "autoconfig" ]
+then
     shift
 
     if [ $# -eq 0 ]
@@ -65,23 +69,22 @@ then
         exit 1
     fi
 
-    grep "Hybridmeter auto config" ~/.bashrc > /dev/null
-    if [ $? -eq 0 ]
+    if [ ! -d $1 ]
     then
-        sed '/^# Hybridmeter auto/,/# End hybridmeter/{d}' ~/.bashrc > ~/.bashrc
+        echo "$1 isn't a valid folder path">&2
     fi
 
-    moodle_path=$1
-    script_path=$(readlink -f $0)
-    script_dir=$(dirname $script_path)
-    git_root=$(dirname "${script_dir}/..")
+    moodle_root=$(readlink -f $1)
+    git_root=$(readlink -f "${SCRIPT_DIR}/../")
 
-    echo -e "\n# Hybridmeter auto config" >> ~/.bashrc
-    echo "export PATH=\"\${PATH}:$script_dir\"" >> ~/.bashrc
-    echo "export HYBRIDMETER_MOODLE_ROOT_PATH=${moodle_path}"  >> ~/.bashrc
-    echo "export HYBRIDMETER_GIT_ROOT_PATH=${git_root}" >> ~/.bashrc
-    echo -e "# End hybridmeter auto config" >> ~/.bashrc
-    echo "Path added"
+
+    sed '/HYBRIDMETER_MOODLE_ROOT/d' "${SCRIPT_DIR}/hybrid_dev.env" > "${SCRIPT_DIR}/hybrid_dev.env"
+    sed '/HYBRIDMETER_GIT_ROOT/d' "${SCRIPT_DIR}/hybrid_dev.env" > "${SCRIPT_DIR}/hybrid_dev.env"
+
+    echo "HYBRIDMETER_MOODLE_ROOT=\"${moodle_root}\"" >> "${SCRIPT_DIR}/hybrid_dev.env"
+    echo "HYBRIDMETER_GIT_ROOT=\"${git_root}\"" >> "${SCRIPT_DIR}/hybrid_dev.env"
+
+    echo "Environment ready"
     exit 0
 fi
 
@@ -95,25 +98,23 @@ if [ $git_root_undefined -eq 1 ]
         exit 3
 fi
 
-#TODO : changer commit par stage
-
-if [ "$1" = "autocommit" ]
+if [ "$1" = "autostage" ]
 then
     while true
     do
-        find ${SOURCE_PATH} -not -path "*hybridmeter/vue/node_modules*" | entr -dr bash ./commit_to_moodle.sh ${SOURCE_PATH} ${REPORT_PATH} ${VUE_PATH}
+        find ${SOURCE_PATH} -not -path "*hybridmeter/vue/node_modules*" | entr -dr bash ${DEVTOOLS_PATH}/stage_to_moodle.sh ${SOURCE_PATH} ${REPORT_PATH} ${VUE_PATH}
     done
     exit 0
-elif [ "$1" = "commit" ]
+elif [ "$1" = "stage" ]
 then
-    bash ${DEVTOOLS_PATH}/commit_to_moodle.sh ${SOURCE_PATH} ${REPORT_PATH} ${VUE_PATH}
+    bash ${DEVTOOLS_PATH}/stage_to_moodle.sh ${SOURCE_PATH} ${REPORT_PATH} ${VUE_PATH}
     error_code=$?
     if [ $error_code -eq 0 ]
     then
-        echo "Changes successfully committed to moodle"
+        echo "Changes successfully staged to moodle"
         exit 0
     else
-        echo "An error occured during the commit">&2
+        echo "An error occured during the stage">&2
         exit 4
     fi
 elif [ "$1" = "build" ]
